[package]
name = "cobble-cpp"
version.workspace = true
edition.workspace = true
license.workspace = true
repository.workspace = true
homepage.workspace = true
publish = false

[lib]
name = "cobble_cpp_ffi"
crate-type = ["staticlib", "rlib"]

[features]
default = []
storage-all = [
    "storage-alluxio",
    "storage-cos",
    "storage-ftp",
    "storage-goosefs",
    "storage-hdfs",
    "storage-oss",
    "storage-s3",
    "storage-sftp",
]
storage-alluxio = ["cobble/storage-alluxio"]
storage-cos = ["cobble/storage-cos"]
storage-ftp = ["cobble/storage-ftp"]
storage-goosefs = ["cobble/storage-goosefs"]
storage-hdfs = ["cobble/storage-hdfs"]
storage-oss = ["cobble/storage-oss"]
storage-s3 = ["cobble/storage-s3"]
storage-sftp = ["cobble/storage-sftp"]

[dependencies]
bytes = { workspace = true }
cobble = { workspace = true, features = ["ffi"] }
cxx = "1.0.186"
opendal = { version = "0.58.1", default-features = false }
serde_json = { workspace = true }
size = { workspace = true }

[build-dependencies]
cxx-build = "1.0.186"
