//! Standalone coordinator/shard protocol over TCP.
//!
//! This module provides a default "standalone" cluster coordination mode:
//! - shards keep long-lived TCP connections to the coordinator;
//! - both sides can send requests over the same full-duplex stream;
//! - every request/response pair is correlated by `request_id`.
//!
//! The coordinator aggregates per-shard checkpoints into a global checkpoint,
//! while each shard wraps a local `Db` instance and serves checkpoint requests.

use cobble::{
    Config, CoordinatorConfig, Db, DbBuilder, DbCoordinator, DbGovernance, Error,
    FileSystemDbGovernance, GlobalSnapshotManifest, Result, ShardSnapshotInput,
};
use serde::{Deserialize, Serialize};
use std::collections::HashMap;
use std::future::Future;
use std::ops::RangeInclusive;
use std::pin::Pin;
use std::sync::atomic::{AtomicBool, Ordering};
use std::sync::{Arc, Mutex};
use std::thread;
use std::time::{Duration, Instant};
use tokio::io::{AsyncBufReadExt, AsyncWriteExt, BufReader};
use tokio::net::{TcpListener, TcpStream};
use tokio::runtime::{Builder, Runtime};
use tokio::sync::{Notify, mpsc, oneshot};
use tokio::task::JoinHandle;
use uuid::Uuid;

/// Poll interval used by accept/wait loops.
const ACCEPT_POLL_DELAY: Duration = Duration::from_millis(25);
/// Retry interval for shard reconnect and best-effort client retries.
const CONNECT_RETRY_DELAY: Duration = Duration::from_millis(100);
/// Default timeout for request/response RPC calls.
const REQUEST_TIMEOUT: Duration = Duration::from_secs(5);

#[derive(Clone, Debug, Eq, PartialEq, Serialize, Deserialize)]
/// Serializable bucket range used on the wire.
struct BucketRange {
    /// Inclusive start bucket id.
    pub start: u16,
    /// Inclusive end bucket id.
    pub end: u16,
}

impl BucketRange {
    fn to_range(&self) -> RangeInclusive<u16> {
        self.start..=self.end
    }
}

impl From<&RangeInclusive<u16>> for BucketRange {
    fn from(range: &RangeInclusive<u16>) -> Self {
        Self {
            start: *range.start(),
            end: *range.end(),
        }
    }
}

#[derive(Clone, Debug, Eq, PartialEq, Serialize, Deserialize)]
/// Shard checkpoint payload exchanged between coordinator and shard.
struct StandaloneShardSnapshot {
    /// Bucket ranges owned by this shard.
    pub ranges: Vec<BucketRange>,
    /// Stable database id for shard identity.
    pub db_id: String,
    /// Snapshot id generated by the shard DB.
    pub snapshot_id: u64,
    /// Snapshot manifest path used by coordinator-side global manifest.
    pub manifest_path: String,
}

impl From<ShardSnapshotInput> for StandaloneShardSnapshot {
    fn from(input: ShardSnapshotInput) -> Self {
        Self {
            ranges: input.ranges.iter().map(BucketRange::from).collect(),
            db_id: input.db_id,
            snapshot_id: input.snapshot_id,
            manifest_path: input.manifest_path,
        }
    }
}

impl From<StandaloneShardSnapshot> for ShardSnapshotInput {
    fn from(snapshot: StandaloneShardSnapshot) -> Self {
        Self {
            ranges: snapshot.ranges.iter().map(BucketRange::to_range).collect(),
            db_id: snapshot.db_id,
            snapshot_id: snapshot.snapshot_id,
            manifest_path: snapshot.manifest_path,
        }
    }
}

/// Protocol requests sent between coordinator and shard.
#[derive(Clone, Debug, Serialize, Deserialize)]
enum StandaloneRequest {
    Ping,
    RegisterDb {
        db_id: String,
        ranges: Vec<BucketRange>,
        total_buckets: u32,
    },
    TakeShardCheckpoint,
}

/// Protocol responses sent between coordinator and shard.
#[derive(Clone, Debug, Serialize, Deserialize)]
enum StandaloneResponse {
    Pong,
    Registered,
    ShardCheckpoint(StandaloneShardSnapshot),
    Error(String),
}

/// Wire request envelope carrying a unique request id.
#[derive(Clone, Debug, Serialize, Deserialize)]
struct StandaloneWireRequest {
    request_id: String,
    request: StandaloneRequest,
}

/// Wire response envelope carrying the request id being answered.
#[derive(Clone, Debug, Serialize, Deserialize)]
struct StandaloneWireResponse {
    request_id: String,
    response: StandaloneResponse,
}

/// One-line JSON messages exchanged on each TCP stream.
#[derive(Clone, Debug, Serialize, Deserialize)]
#[serde(tag = "message_type", rename_all = "snake_case")]
enum StandaloneWireEnvelope {
    Request(StandaloneWireRequest),
    Response(StandaloneWireResponse),
}

type AsyncRequestHandler = Arc<
    dyn Fn(StandaloneRequest) -> Pin<Box<dyn Future<Output = Result<StandaloneResponse>> + Send>>
        + Send
        + Sync,
>;

#[derive(Clone)]
struct Connection {
    // Queue of outbound protocol frames, consumed by the writer task.
    outbound: mpsc::UnboundedSender<StandaloneWireEnvelope>,
    // Request-id -> waiter map used by request/response matching.
    pending: Arc<Mutex<HashMap<String, oneshot::Sender<StandaloneResponse>>>>,
    // Fired when the reader loop detects closure and drains pending requests.
    closed: Arc<Notify>,
    // Set to true when the connection is shutting down.
    closing: Arc<AtomicBool>,
    // Dedicated close signal so disconnect can preempt normal outbound traffic.
    close_signal: Arc<Notify>,
}

impl Connection {
    async fn request(
        &self,
        request: StandaloneRequest,
        timeout: Duration,
    ) -> Result<StandaloneResponse> {
        if self.closing.load(Ordering::SeqCst) {
            return Err(Error::IoError("connection is closing".to_string()));
        }
        let request_id = Uuid::new_v4().to_string();
        let (tx, rx) = oneshot::channel();
        self.pending
            .lock()
            .expect("pending requests lock")
            .insert(request_id.clone(), tx);
        self.outbound
            .send(StandaloneWireEnvelope::Request(StandaloneWireRequest {
                request_id: request_id.clone(),
                request,
            }))
            .map_err(|_| Error::IoError("connection outbound channel closed".to_string()))?;

        let response = match tokio::time::timeout(timeout, rx).await {
            Ok(Ok(response)) => response,
            Ok(Err(_)) => {
                self.pending
                    .lock()
                    .expect("pending requests lock")
                    .remove(&request_id);
                return Err(Error::IoError(
                    "request response channel closed".to_string(),
                ));
            }
            Err(_) => {
                self.pending
                    .lock()
                    .expect("pending requests lock")
                    .remove(&request_id);
                return Err(Error::IoError("request timed out".to_string()));
            }
        };
        Ok(response)
    }

    async fn wait_closed(&self) {
        self.closed.notified().await;
    }

    fn close(&self) {
        self.closing.store(true, Ordering::SeqCst);
        self.close_signal.notify_waiters();
    }
}

fn establish_connection(
    stream: TcpStream,
    request_handler: AsyncRequestHandler,
    on_close: Option<Arc<dyn Fn() + Send + Sync>>,
) -> Connection {
    let (read_half, mut write_half) = stream.into_split();
    let (outbound_tx, mut outbound_rx) = mpsc::unbounded_channel::<StandaloneWireEnvelope>();
    let pending: Arc<Mutex<HashMap<String, oneshot::Sender<StandaloneResponse>>>> =
        Arc::new(Mutex::new(HashMap::new()));
    let closed = Arc::new(Notify::new());
    let closing = Arc::new(AtomicBool::new(false));
    let close_signal = Arc::new(Notify::new());
    let writer_closing = Arc::clone(&closing);
    let writer_close_signal = Arc::clone(&close_signal);

    // Writer loop: serialize outbound envelopes to newline-delimited JSON.
    let writer_task = tokio::spawn(async move {
        loop {
            tokio::select! {
                biased;
                _ = writer_close_signal.notified() => break,
                maybe_message = outbound_rx.recv() => {
                    let Some(message) = maybe_message else { break };
                    if writer_closing.load(Ordering::SeqCst) {
                        break;
                    }
                    if write_envelope_to_stream(&mut write_half, &message)
                        .await
                        .is_err()
                    {
                        break;
                    }
                }
            }
        }
    });

    let reader_pending = Arc::clone(&pending);
    let reader_closed = Arc::clone(&closed);
    let reader_outbound = outbound_tx.clone();
    let reader_on_close = on_close.clone();
    let reader_closing = Arc::clone(&closing);
    let reader_close_signal = Arc::clone(&close_signal);
    // Reader loop: decode incoming frames, route responses or execute requests.
    tokio::spawn(async move {
        let mut reader = BufReader::new(read_half);
        let mut line = String::new();
        loop {
            line.clear();
            let read = match reader.read_line(&mut line).await {
                Ok(read) => read,
                Err(_) => break,
            };
            if read == 0 {
                break;
            }
            let envelope: StandaloneWireEnvelope = match serde_json::from_str(line.trim_end()) {
                Ok(envelope) => envelope,
                Err(_) => break,
            };
            match envelope {
                StandaloneWireEnvelope::Response(response) => {
                    if let Some(sender) = reader_pending
                        .lock()
                        .expect("pending requests lock")
                        .remove(&response.request_id)
                    {
                        let _ = sender.send(response.response);
                    }
                }
                StandaloneWireEnvelope::Request(request) => {
                    let response = match request_handler(request.request).await {
                        Ok(response) => response,
                        Err(err) => StandaloneResponse::Error(err.to_string()),
                    };
                    let _ = reader_outbound.send(StandaloneWireEnvelope::Response(
                        StandaloneWireResponse {
                            request_id: request.request_id,
                            response,
                        },
                    ));
                }
            }
        }

        // Fail all pending requests once the stream closes.
        let pending_entries = {
            let mut guard = reader_pending.lock().expect("pending requests lock");
            std::mem::take(&mut *guard)
        };
        for (_, sender) in pending_entries {
            let _ = sender.send(StandaloneResponse::Error("connection closed".to_string()));
        }

        reader_closing.store(true, Ordering::SeqCst);
        reader_close_signal.notify_waiters();
        writer_task.abort();
        if let Some(on_close) = reader_on_close {
            on_close();
        }
        reader_closed.notify_waiters();
    });

    Connection {
        outbound: outbound_tx,
        pending,
        closed,
        closing,
        close_signal,
    }
}

pub struct StandaloneCoordinator {
    // Shared Tokio runtime used by listener and async RPC workers.
    runtime: Arc<Runtime>,
    // Core coordinator logic from cobble-common (global snapshot materialization).
    coordinator: Arc<DbCoordinator>,
    // Local filesystem governance write path kept on coordinator side.
    local_governance: Arc<FileSystemDbGovernance>,
    // Active shard sessions keyed by db_id.
    connected_shards: Arc<Mutex<HashMap<String, Connection>>>,
    // Cooperative stop signal for async loops.
    shutdown: Arc<AtomicBool>,
    // Background listener task started by serve().
    listener_task: Option<JoinHandle<()>>,
}

impl StandaloneCoordinator {
    pub fn new(config: CoordinatorConfig) -> Result<Self> {
        let runtime = Arc::new(new_runtime()?);
        let local_governance = Arc::new(FileSystemDbGovernance::from_volumes(&config.volumes)?);
        Ok(Self {
            runtime,
            coordinator: Arc::new(DbCoordinator::open(config)?),
            local_governance,
            connected_shards: Arc::new(Mutex::new(HashMap::new())),
            shutdown: Arc::new(AtomicBool::new(false)),
            listener_task: None,
        })
    }

    pub fn serve(&mut self, bind_addr: &str) -> Result<()> {
        if self.listener_task.is_some() {
            return Err(Error::InvalidState(
                "standalone coordinator server already running".to_string(),
            ));
        }
        self.shutdown.store(false, Ordering::SeqCst);
        let bind_addr = bind_addr.to_string();
        let shutdown = Arc::clone(&self.shutdown);
        let local_governance = Arc::clone(&self.local_governance);
        let connected_shards = Arc::clone(&self.connected_shards);
        // Listener loop runs in background; serve() itself is non-blocking.
        self.listener_task = Some(self.runtime.spawn(async move {
            let listener = match TcpListener::bind(&bind_addr).await {
                Ok(listener) => listener,
                Err(_) => return,
            };
            while !shutdown.load(Ordering::SeqCst) {
                match tokio::time::timeout(ACCEPT_POLL_DELAY, listener.accept()).await {
                    Ok(Ok((stream, _))) => {
                        // Each accepted TCP stream is upgraded into a request/response session.
                        setup_coordinator_connection(
                            stream,
                            Arc::clone(&local_governance),
                            Arc::clone(&connected_shards),
                        )
                        .await;
                    }
                    Ok(Err(_)) => break,
                    Err(_) => continue,
                }
            }
        }));
        Ok(())
    }

    pub fn shutdown(&mut self) -> Result<()> {
        self.shutdown.store(true, Ordering::SeqCst);
        if let Some(listener_task) = self.listener_task.take() {
            listener_task.abort();
            self.runtime.block_on(async {
                let _ = listener_task.await;
            });
        }
        let shards: Vec<Connection> = self
            .connected_shards
            .lock()
            .expect("connected shards lock")
            .drain()
            .map(|(_, connection)| connection)
            .collect();
        for connection in shards {
            connection.close();
        }
        Ok(())
    }

    #[cfg(test)]
    fn connected_shard_count(&self) -> usize {
        self.connected_shards
            .lock()
            .expect("connected shards lock")
            .len()
    }

    #[cfg(test)]
    fn wait_for_shards(&self, expected: usize, timeout: Duration) -> Result<()> {
        let deadline = Instant::now() + timeout;
        while Instant::now() <= deadline {
            if self.connected_shard_count() >= expected {
                return Ok(());
            }
            thread::sleep(ACCEPT_POLL_DELAY);
        }
        Err(Error::IoError(format!(
            "timeout waiting for {} connected shards, got {}",
            expected,
            self.connected_shard_count()
        )))
    }

    pub fn load_current_global_snapshot(&self) -> Result<Option<GlobalSnapshotManifest>> {
        self.coordinator.load_current_global_snapshot()
    }

    pub fn take_global_checkpoint(&self, total_buckets: u32, timeout: Duration) -> Result<u64> {
        self.runtime.block_on(take_global_checkpoint_inner(
            Arc::clone(&self.coordinator),
            Arc::clone(&self.connected_shards),
            total_buckets,
            timeout,
        ))
    }

    #[cfg(test)]
    fn ping_connected_shards(&self, timeout: Duration) -> Result<usize> {
        self.runtime.block_on(ping_connected_shards_inner(
            Arc::clone(&self.connected_shards),
            timeout,
        ))
    }

    /// Runs global checkpoint asynchronously and always completes via callback.
    ///
    /// If any shard is disconnected or does not reply before timeout, callback gets `Err`.
    pub fn take_global_checkpoint_with_callback<F>(
        &self,
        total_buckets: u32,
        timeout: Duration,
        callback: F,
    ) -> Result<()>
    where
        F: Fn(Result<u64>) + Send + Sync + 'static,
    {
        let coordinator = Arc::clone(&self.coordinator);
        let connected_shards = Arc::clone(&self.connected_shards);
        self.runtime.spawn(async move {
            let result =
                take_global_checkpoint_inner(coordinator, connected_shards, total_buckets, timeout)
                    .await;
            callback(result);
        });
        Ok(())
    }
}

impl Drop for StandaloneCoordinator {
    fn drop(&mut self) {
        let _ = self.shutdown();
    }
}

async fn setup_coordinator_connection(
    stream: TcpStream,
    local_governance: Arc<FileSystemDbGovernance>,
    connected_shards: Arc<Mutex<HashMap<String, Connection>>>,
) {
    // `registered_db_id` records which shard identity this connection has registered as.
    let registered_db_id: Arc<Mutex<Option<String>>> = Arc::new(Mutex::new(None));
    // `connection_slot` is populated immediately after establishment, then consumed on register.
    let connection_slot: Arc<Mutex<Option<Connection>>> = Arc::new(Mutex::new(None));

    let handler_db_id = Arc::clone(&registered_db_id);
    let handler_connection_slot = Arc::clone(&connection_slot);
    let handler_connected_shards = Arc::clone(&connected_shards);
    let handler_local_governance = Arc::clone(&local_governance);

    let handler: AsyncRequestHandler = Arc::new(move |request| {
        let handler_db_id = Arc::clone(&handler_db_id);
        let handler_connection_slot = Arc::clone(&handler_connection_slot);
        let handler_connected_shards = Arc::clone(&handler_connected_shards);
        let handler_local_governance = Arc::clone(&handler_local_governance);
        Box::pin(async move {
            match request {
                StandaloneRequest::Ping => Ok(StandaloneResponse::Pong),
                StandaloneRequest::TakeShardCheckpoint => Err(Error::IoError(
                    "coordinator endpoint does not serve shard checkpoints".to_string(),
                )),
                StandaloneRequest::RegisterDb {
                    db_id,
                    ranges,
                    total_buckets,
                } => {
                    let range_values: Vec<RangeInclusive<u16>> =
                        ranges.iter().map(BucketRange::to_range).collect();
                    let governance = Arc::clone(&handler_local_governance);
                    let db_id_for_register = db_id.clone();
                    let register_result = tokio::task::spawn_blocking(move || {
                        governance.register_db(&db_id_for_register, &range_values, total_buckets)
                    })
                    .await
                    .map_err(|_| Error::IoError("register_db task panicked".to_string()))?;
                    register_result?;

                    // Only after successful governance registration do we accept shard session.
                    let connection = handler_connection_slot
                        .lock()
                        .expect("connection slot lock")
                        .take();
                    if let Some(connection) = connection {
                        handler_connected_shards
                            .lock()
                            .expect("connected shards lock")
                            .insert(db_id.clone(), connection);
                    }
                    *handler_db_id.lock().expect("registered db id lock") = Some(db_id);
                    Ok(StandaloneResponse::Registered)
                }
            }
        })
    });

    let close_db_id = Arc::clone(&registered_db_id);
    let close_connected_shards = Arc::clone(&connected_shards);
    let on_close: Arc<dyn Fn() + Send + Sync> = Arc::new(move || {
        if let Some(db_id) = close_db_id.lock().expect("registered db id lock").take() {
            close_connected_shards
                .lock()
                .expect("connected shards lock")
                .remove(&db_id);
        }
    });

    let connection = establish_connection(stream, handler, Some(on_close));
    *connection_slot.lock().expect("connection slot lock") = Some(connection);
}

async fn take_global_checkpoint_inner(
    coordinator: Arc<DbCoordinator>,
    connected_shards: Arc<Mutex<HashMap<String, Connection>>>,
    total_buckets: u32,
    timeout: Duration,
) -> Result<u64> {
    // Take a stable snapshot of currently connected shards.
    let entries: Vec<(String, Connection)> = connected_shards
        .lock()
        .expect("connected shards lock")
        .iter()
        .map(|(db_id, connection)| (db_id.clone(), connection.clone()))
        .collect();

    if entries.is_empty() {
        return Err(Error::IoError(
            "at least one connected shard is required".to_string(),
        ));
    }

    let deadline = Instant::now() + timeout;
    let mut workers = Vec::with_capacity(entries.len());
    for (db_id, connection) in entries {
        // Per-shard request budget is bounded by the shared global deadline.
        let remaining = deadline.saturating_duration_since(Instant::now());
        workers.push(tokio::spawn(async move {
            if remaining.is_zero() {
                return Err((
                    db_id,
                    Error::IoError("global checkpoint timed out".to_string()),
                ));
            }
            let response = connection
                .request(StandaloneRequest::TakeShardCheckpoint, remaining)
                .await
                .map_err(|err| (db_id.clone(), err))?;
            match response {
                StandaloneResponse::ShardCheckpoint(snapshot) => Ok((db_id, snapshot)),
                StandaloneResponse::Error(message) => Err((db_id, Error::IoError(message))),
                _ => Err((
                    db_id,
                    Error::IoError("unexpected response for shard checkpoint".to_string()),
                )),
            }
        }));
    }

    let mut first_error: Option<Error> = None;
    let mut failed_db_ids = Vec::new();
    let mut shard_snapshots = Vec::new();

    for worker in workers {
        match worker.await {
            Ok(Ok((_, snapshot))) => shard_snapshots.push(snapshot.into()),
            Ok(Err((db_id, err))) => {
                failed_db_ids.push(db_id);
                if first_error.is_none() {
                    first_error = Some(err);
                }
            }
            Err(_) => {
                if first_error.is_none() {
                    first_error = Some(Error::IoError(
                        "checkpoint worker task panicked".to_string(),
                    ));
                }
            }
        }
    }

    // Drop failed sessions so they must reconnect and re-register.
    if !failed_db_ids.is_empty() {
        let mut guard = connected_shards.lock().expect("connected shards lock");
        for db_id in failed_db_ids {
            if let Some(connection) = guard.remove(&db_id) {
                connection.close();
            }
        }
    }

    if let Some(err) = first_error {
        return Err(err);
    }

    if shard_snapshots.is_empty() {
        return Err(Error::IoError("no shard snapshots collected".to_string()));
    }

    // Global manifest is materialized only after every shard snapshot is collected.
    let global = tokio::task::spawn_blocking(move || {
        let snapshot = coordinator.take_global_snapshot(total_buckets, shard_snapshots)?;
        coordinator.materialize_global_snapshot(&snapshot)?;
        Ok::<u64, Error>(snapshot.id)
    })
    .await
    .map_err(|_| Error::IoError("global checkpoint task panicked".to_string()))??;

    Ok(global)
}

#[cfg(test)]
async fn ping_connected_shards_inner(
    connected_shards: Arc<Mutex<HashMap<String, Connection>>>,
    timeout: Duration,
) -> Result<usize> {
    let entries: Vec<(String, Connection)> = connected_shards
        .lock()
        .expect("connected shards lock")
        .iter()
        .map(|(db_id, connection)| (db_id.clone(), connection.clone()))
        .collect();

    if entries.is_empty() {
        return Ok(0);
    }

    let mut workers = Vec::with_capacity(entries.len());
    for (db_id, connection) in entries {
        workers.push(tokio::spawn(async move {
            let response = connection
                .request(StandaloneRequest::Ping, timeout)
                .await
                .map_err(|err| (db_id.clone(), err))?;
            match response {
                StandaloneResponse::Pong => Ok(db_id),
                StandaloneResponse::Error(message) => Err((db_id, Error::IoError(message))),
                _ => Err((
                    db_id,
                    Error::IoError("unexpected ping response".to_string()),
                )),
            }
        }));
    }

    let mut success = 0usize;
    let mut first_error: Option<Error> = None;
    let mut failed_db_ids = Vec::new();
    for worker in workers {
        match worker.await {
            Ok(Ok(_)) => success += 1,
            Ok(Err((db_id, err))) => {
                failed_db_ids.push(db_id);
                if first_error.is_none() {
                    first_error = Some(err);
                }
            }
            Err(_) => {
                if first_error.is_none() {
                    first_error = Some(Error::IoError("ping worker task panicked".to_string()));
                }
            }
        }
    }

    if !failed_db_ids.is_empty() {
        let mut guard = connected_shards.lock().expect("connected shards lock");
        for db_id in failed_db_ids {
            if let Some(connection) = guard.remove(&db_id) {
                connection.close();
            }
        }
    }

    if let Some(err) = first_error {
        return Err(err);
    }
    Ok(success)
}

#[derive(Clone)]
struct StandaloneClient {
    // Coordinator endpoint.
    addr: String,
    // Timeout used for unary request helper APIs.
    timeout: Duration,
    // Dedicated runtime so sync call sites can execute async network requests.
    runtime: Arc<Runtime>,
}

impl StandaloneClient {
    fn new<S>(addr: S) -> Self
    where
        S: Into<String>,
    {
        Self {
            addr: addr.into(),
            timeout: REQUEST_TIMEOUT,
            runtime: Arc::new(new_runtime().expect("create standalone client runtime")),
        }
    }

    fn register_db(
        &self,
        db_id: &str,
        ranges: &[RangeInclusive<u16>],
        total_buckets: u32,
    ) -> Result<()> {
        let request = StandaloneRequest::RegisterDb {
            db_id: db_id.to_string(),
            ranges: ranges.iter().map(BucketRange::from).collect(),
            total_buckets,
        };
        match self.send_request(&request)? {
            StandaloneResponse::Registered => Ok(()),
            _ => Err(Error::IoError("unexpected register response".to_string())),
        }
    }

    fn send_request(&self, request: &StandaloneRequest) -> Result<StandaloneResponse> {
        self.runtime.block_on(send_request_async(
            &self.addr,
            self.timeout,
            request.clone(),
        ))
    }
}

async fn send_request_async(
    addr: &str,
    timeout: Duration,
    request: StandaloneRequest,
) -> Result<StandaloneResponse> {
    let stream = connect_with_retry_async(addr, 20).await?;
    let (read_half, mut write_half) = stream.into_split();
    let request_id = Uuid::new_v4().to_string();
    let envelope = StandaloneWireEnvelope::Request(StandaloneWireRequest {
        request_id: request_id.clone(),
        request,
    });
    write_envelope_to_stream(&mut write_half, &envelope).await?;

    let mut reader = BufReader::new(read_half);
    let mut line = String::new();
    let wire_response = tokio::time::timeout(timeout, async {
        loop {
            line.clear();
            let read = reader.read_line(&mut line).await.map_err(to_io_error)?;
            if read == 0 {
                return Err(Error::IoError("connection closed".to_string()));
            }
            let envelope: StandaloneWireEnvelope = serde_json::from_str(line.trim_end())
                .map_err(|err| Error::IoError(format!("failed to decode response: {}", err)))?;
            if let StandaloneWireEnvelope::Response(response) = envelope {
                return Ok(response);
            }
        }
    })
    .await
    .map_err(|_| Error::IoError("request timed out".to_string()))??;

    if wire_response.request_id != request_id {
        return Err(Error::IoError(
            "response request_id does not match request".to_string(),
        ));
    }

    match wire_response.response {
        StandaloneResponse::Error(message) => Err(Error::IoError(message)),
        other => Ok(other),
    }
}

#[derive(Clone)]
struct StandaloneGovernance {
    // Transport client used by Db startup governance registration.
    client: StandaloneClient,
}

impl StandaloneGovernance {
    fn new(client: StandaloneClient) -> Self {
        Self { client }
    }
}

impl DbGovernance for StandaloneGovernance {
    fn register_db(
        &self,
        db_id: &str,
        ranges: &[RangeInclusive<u16>],
        total_buckets: u32,
    ) -> Result<()> {
        self.client.register_db(db_id, ranges, total_buckets)
    }
}

#[derive(Clone)]
struct ShardRegistration {
    // Coordinator endpoint to keep a persistent session with.
    coordinator_addr: String,
    // Bucket ownership metadata announced at register_db.
    ranges: Vec<RangeInclusive<u16>>,
    // Total bucket count expected by coordinator governance checks.
    total_buckets: u32,
}

pub struct StandaloneShardNode {
    // Local writable DB instance.
    db: Arc<Db>,
    // Present when node is responsible for coordinator registration/reconnect.
    registration: Option<ShardRegistration>,
    // Runtime for connector and bidirectional protocol tasks.
    runtime: Arc<Runtime>,
    // Cooperative stop flag for connector loop.
    shutdown: Arc<AtomicBool>,
    // Background connector task started by serve().
    connector_task: Option<JoinHandle<()>>,
}

impl StandaloneShardNode {
    pub fn open<S>(
        config: Config,
        bucket_ranges: Vec<RangeInclusive<u16>>,
        coordinator_addr: S,
    ) -> Result<Self>
    where
        S: Into<String>,
    {
        let coordinator_addr = coordinator_addr.into();
        let coordinator_client = StandaloneClient::new(&coordinator_addr);
        let governance = Arc::new(StandaloneGovernance::new(coordinator_client.clone()));
        let db = Arc::new(
            DbBuilder::new(config.clone())
                .bucket_ranges(bucket_ranges.clone())
                .governance(governance as Arc<dyn DbGovernance>)
                .open()?,
        );
        Ok(Self {
            db,
            registration: Some(ShardRegistration {
                coordinator_addr,
                ranges: bucket_ranges,
                total_buckets: config.total_buckets,
            }),
            runtime: Arc::new(new_runtime()?),
            shutdown: Arc::new(AtomicBool::new(false)),
            connector_task: None,
        })
    }

    /// Resume a shard DB from existing local state and reconnect to coordinator.
    ///
    /// This is useful in tests and rolling-restart flows where the previous `Db`
    /// was cleanly closed and needs to rejoin coordinator governance with the
    /// same `db_id`.
    pub fn resume<S>(
        config: Config,
        db_id: String,
        bucket_ranges: Vec<RangeInclusive<u16>>,
        coordinator_addr: S,
    ) -> Result<Self>
    where
        S: Into<String>,
    {
        let coordinator_addr = coordinator_addr.into();
        let db = Arc::new(Db::resume(config.clone(), db_id)?);
        Ok(Self {
            db,
            registration: Some(ShardRegistration {
                coordinator_addr,
                ranges: bucket_ranges,
                total_buckets: config.total_buckets,
            }),
            runtime: Arc::new(new_runtime()?),
            shutdown: Arc::new(AtomicBool::new(false)),
            connector_task: None,
        })
    }

    pub fn serve(&mut self) -> Result<()> {
        if self.connector_task.is_some() {
            return Err(Error::InvalidState(
                "standalone shard connector already running".to_string(),
            ));
        }
        let registration = self.registration.clone().ok_or_else(|| {
            Error::InvalidState(
                "standalone shard node missing coordinator registration config".to_string(),
            )
        })?;

        self.shutdown.store(false, Ordering::SeqCst);
        let shutdown = Arc::clone(&self.shutdown);
        let db = Arc::clone(&self.db);
        self.connector_task = Some(self.runtime.spawn(async move {
            let _ = run_shard_connector(db, registration, shutdown).await;
        }));
        Ok(())
    }

    pub fn shutdown(&mut self) -> Result<()> {
        self.shutdown.store(true, Ordering::SeqCst);
        if let Some(connector_task) = self.connector_task.take() {
            // Do not block on graceful drain here: immediate disconnect is preferred.
            connector_task.abort();
            self.runtime.block_on(async {
                let _ = connector_task.await;
            });
        }
        Ok(())
    }

    pub fn db(&self) -> &Db {
        self.db.as_ref()
    }
}

impl Drop for StandaloneShardNode {
    fn drop(&mut self) {
        let _ = self.shutdown();
    }
}

async fn run_shard_connector(
    db: Arc<Db>,
    registration: ShardRegistration,
    shutdown: Arc<AtomicBool>,
) -> Result<()> {
    // Reconnect loop: keep shard session alive until shutdown is requested.
    while !shutdown.load(Ordering::SeqCst) {
        let stream = match TcpStream::connect(&registration.coordinator_addr).await {
            Ok(stream) => stream,
            Err(_) => {
                tokio::time::sleep(CONNECT_RETRY_DELAY).await;
                continue;
            }
        };

        let db_for_handler = Arc::clone(&db);
        let handler: AsyncRequestHandler = Arc::new(move |request| {
            let db_for_handler = Arc::clone(&db_for_handler);
            Box::pin(async move {
                match request {
                    StandaloneRequest::Ping => Ok(StandaloneResponse::Pong),
                    StandaloneRequest::TakeShardCheckpoint => {
                        let db_for_snapshot = Arc::clone(&db_for_handler);
                        let snapshot = tokio::task::spawn_blocking(move || {
                            take_shard_checkpoint_for_db(db_for_snapshot.as_ref())
                        })
                        .await
                        .map_err(|_| {
                            Error::IoError("take_shard_checkpoint task panicked".to_string())
                        })??;
                        Ok(StandaloneResponse::ShardCheckpoint(snapshot))
                    }
                    StandaloneRequest::RegisterDb { .. } => Err(Error::IoError(
                        "shard endpoint does not accept register_db".to_string(),
                    )),
                }
            })
        });

        let connection = establish_connection(stream, handler, None);
        let register_response = connection
            .request(
                StandaloneRequest::RegisterDb {
                    db_id: db.id().to_string(),
                    ranges: registration.ranges.iter().map(BucketRange::from).collect(),
                    total_buckets: registration.total_buckets,
                },
                REQUEST_TIMEOUT,
            )
            .await;

        match register_response {
            Ok(StandaloneResponse::Registered) => {}
            Ok(StandaloneResponse::Error(_)) | Ok(_) | Err(_) => {
                connection.close();
                tokio::time::sleep(CONNECT_RETRY_DELAY).await;
                continue;
            }
        }

        // Stay connected until link drop or explicit shutdown signal.
        let shutdown_triggered = tokio::select! {
            _ = connection.wait_closed() => false,
            _ = wait_for_shutdown(Arc::clone(&shutdown)) => true,
        };

        if shutdown_triggered {
            connection.close();
        }

        if shutdown.load(Ordering::SeqCst) {
            break;
        }
        tokio::time::sleep(CONNECT_RETRY_DELAY).await;
    }

    Ok(())
}

async fn wait_for_shutdown(shutdown: Arc<AtomicBool>) {
    while !shutdown.load(Ordering::SeqCst) {
        tokio::time::sleep(ACCEPT_POLL_DELAY).await;
    }
}

fn take_shard_checkpoint_for_db(db: &Db) -> Result<StandaloneShardSnapshot> {
    let snapshot_id = db.snapshot()?;
    let mut last_error = None;
    for attempt in 0..=50 {
        match db.shard_snapshot_input(snapshot_id) {
            Ok(input) => return Ok(input.into()),
            Err(err) => {
                if attempt == 50 {
                    return Err(err);
                }
                if !matches!(err, Error::IoError(ref msg) if msg.contains("Snapshot manifest not tracked"))
                {
                    return Err(err);
                }
                last_error = Some(err);
                thread::sleep(Duration::from_millis(20));
            }
        }
    }
    Err(last_error
        .unwrap_or_else(|| Error::IoError("failed to materialize shard checkpoint".to_string())))
}

async fn connect_with_retry_async(addr: &str, retries: usize) -> Result<TcpStream> {
    for attempt in 0..=retries {
        match TcpStream::connect(addr).await {
            Ok(stream) => return Ok(stream),
            Err(err) => {
                if attempt == retries {
                    return Err(to_io_error(err));
                }
                tokio::time::sleep(CONNECT_RETRY_DELAY).await;
            }
        }
    }
    Err(Error::IoError("failed to connect".to_string()))
}

async fn write_envelope_to_stream<W>(
    writer: &mut W,
    envelope: &StandaloneWireEnvelope,
) -> Result<()>
where
    W: AsyncWriteExt + Unpin,
{
    let payload = serde_json::to_vec(envelope)
        .map_err(|err| Error::IoError(format!("failed to encode message: {}", err)))?;
    writer.write_all(&payload).await.map_err(to_io_error)?;
    writer.write_all(b"\n").await.map_err(to_io_error)?;
    Ok(())
}

fn new_runtime() -> Result<Runtime> {
    Builder::new_multi_thread()
        .enable_all()
        .worker_threads(2)
        .build()
        .map_err(|err| Error::IoError(format!("failed to create runtime: {}", err)))
}

fn to_io_error(err: std::io::Error) -> Error {
    Error::IoError(err.to_string())
}

#[cfg(test)]
mod tests {
    use super::*;
    use cobble::VolumeDescriptor;
    use cobble::VolumeUsageKind;
    use std::sync::mpsc;

    fn test_server_root(prefix: &str) -> String {
        format!("/tmp/{}_{}", prefix, Uuid::new_v4())
    }

    fn free_addr() -> String {
        let listener = std::net::TcpListener::bind("127.0.0.1:0").expect("bind random addr");
        let addr = listener.local_addr().expect("local addr");
        drop(listener);
        addr.to_string()
    }

    fn build_coordinator(root: &str) -> StandaloneCoordinator {
        let _ = std::fs::remove_dir_all(root);
        StandaloneCoordinator::new(CoordinatorConfig {
            volumes: vec![VolumeDescriptor::new(
                format!("file://{}", root),
                vec![
                    VolumeUsageKind::Meta,
                    VolumeUsageKind::PrimaryDataPriorityHigh,
                ],
            )],
        })
        .expect("open standalone coordinator")
    }

    #[test]
    fn governance_rejects_overlap() {
        let root = test_server_root("standalone_governance_overlap");
        let mut coordinator = build_coordinator(&root);
        let addr = free_addr();
        coordinator.serve(&addr).expect("start coordinator server");

        let client = StandaloneClient::new(&addr);
        client.register_db("db-a", &[0u16..=3u16], 8).unwrap();
        let err = client.register_db("db-b", &[3u16..=5u16], 8).unwrap_err();
        assert!(matches!(err, Error::IoError(_)));

        coordinator.shutdown().unwrap();
        let _ = std::fs::remove_dir_all(root);
    }

    #[test]
    fn coordinator_broadcasts_shard_checkpoints() {
        let coord_root = test_server_root("standalone_coordinator_checkpoint");
        let shard_a_root = test_server_root("standalone_shard_a_checkpoint");
        let shard_b_root = test_server_root("standalone_shard_b_checkpoint");

        let mut coordinator = build_coordinator(&coord_root);
        let coordinator_addr = free_addr();
        coordinator
            .serve(&coordinator_addr)
            .expect("start coordinator server");

        let config_a = Config {
            total_buckets: 4,
            volumes: VolumeDescriptor::single_volume(format!("file://{}", shard_a_root)),
            ..Config::default()
        };
        let config_b = Config {
            total_buckets: 4,
            volumes: VolumeDescriptor::single_volume(format!("file://{}", shard_b_root)),
            ..Config::default()
        };

        let mut shard_a =
            StandaloneShardNode::open(config_a, vec![0u16..=1u16], coordinator_addr.clone())
                .expect("open shard a node");
        let mut shard_b =
            StandaloneShardNode::open(config_b, vec![2u16..=3u16], coordinator_addr.clone())
                .expect("open shard b node");

        shard_a.serve().expect("serve shard a connector");
        shard_b.serve().expect("serve shard b connector");

        coordinator
            .wait_for_shards(2, Duration::from_secs(3))
            .expect("wait for shard registration");

        let (tx, rx) = mpsc::channel();
        coordinator
            .take_global_checkpoint_with_callback(4, Duration::from_secs(5), move |result| {
                tx.send(result).expect("send callback result");
            })
            .expect("start async checkpoint");
        let checkpoint_id = rx
            .recv_timeout(Duration::from_secs(8))
            .expect("receive checkpoint callback")
            .expect("checkpoint should succeed");

        let manifest = coordinator
            .load_current_global_snapshot()
            .expect("load current checkpoint")
            .expect("checkpoint manifest exists");

        assert_eq!(manifest.id, checkpoint_id);
        assert_eq!(manifest.shard_snapshots.len(), 2);

        shard_a.shutdown().unwrap();
        shard_b.shutdown().unwrap();
        coordinator.shutdown().unwrap();
        shard_a.db().close().expect("close shard a db");
        shard_b.db().close().expect("close shard b db");

        let _ = std::fs::remove_dir_all(coord_root);
        let _ = std::fs::remove_dir_all(shard_a_root);
        let _ = std::fs::remove_dir_all(shard_b_root);
    }

    #[test]
    fn full_duplex_link_supports_ping_and_checkpoint() {
        let coord_root = test_server_root("standalone_full_duplex_coord");
        let shard_root = test_server_root("standalone_full_duplex_shard");

        let mut coordinator = build_coordinator(&coord_root);
        let coordinator_addr = free_addr();
        coordinator
            .serve(&coordinator_addr)
            .expect("start coordinator");

        let config = Config {
            total_buckets: 4,
            volumes: VolumeDescriptor::single_volume(format!("file://{}", shard_root)),
            ..Config::default()
        };
        let mut shard =
            StandaloneShardNode::open(config, vec![0u16..=3u16], coordinator_addr.clone())
                .expect("open shard node");
        shard.serve().expect("start shard connector");

        coordinator
            .wait_for_shards(1, Duration::from_secs(3))
            .expect("wait for shard");
        assert_eq!(
            coordinator
                .ping_connected_shards(Duration::from_secs(2))
                .expect("ping connected shards"),
            1
        );

        let checkpoint_id = coordinator
            .take_global_checkpoint(4, Duration::from_secs(5))
            .expect("take global checkpoint");
        let manifest = coordinator
            .load_current_global_snapshot()
            .expect("load checkpoint")
            .expect("checkpoint manifest exists");
        assert_eq!(manifest.id, checkpoint_id);
        assert_eq!(manifest.shard_snapshots.len(), 1);

        assert_eq!(
            coordinator
                .ping_connected_shards(Duration::from_secs(2))
                .expect("ping connected shards after checkpoint"),
            1
        );

        shard.shutdown().unwrap();
        coordinator.shutdown().unwrap();
        shard.db().close().expect("close shard db");
        let _ = std::fs::remove_dir_all(coord_root);
        let _ = std::fs::remove_dir_all(shard_root);
    }

    #[test]
    fn shard_reconnects_after_coordinator_restart() {
        let coord_root = test_server_root("standalone_reconnect_coord");
        let shard_root = test_server_root("standalone_reconnect_shard");

        let mut coordinator = build_coordinator(&coord_root);
        let coordinator_addr = free_addr();
        coordinator
            .serve(&coordinator_addr)
            .expect("start coordinator");

        let config = Config {
            total_buckets: 4,
            volumes: VolumeDescriptor::single_volume(format!("file://{}", shard_root)),
            ..Config::default()
        };
        let mut shard =
            StandaloneShardNode::open(config, vec![0u16..=3u16], coordinator_addr.clone())
                .expect("open shard node");
        shard.serve().expect("start shard connector");

        coordinator
            .wait_for_shards(1, Duration::from_secs(3))
            .expect("initial shard connect");
        coordinator.shutdown().expect("shutdown coordinator");
        coordinator
            .serve(&coordinator_addr)
            .expect("restart coordinator");

        coordinator
            .wait_for_shards(1, Duration::from_secs(8))
            .expect("shard reconnect after restart");
        assert_eq!(
            coordinator
                .ping_connected_shards(Duration::from_secs(2))
                .expect("ping after reconnect"),
            1
        );

        shard.shutdown().unwrap();
        coordinator.shutdown().unwrap();
        shard.db().close().expect("close shard db");
        let _ = std::fs::remove_dir_all(coord_root);
        let _ = std::fs::remove_dir_all(shard_root);
    }
}
