from enum import IntEnum
from os import PathLike
from typing import Final, TypeAlias

__version__: Final[str]

class CobbleError(Exception):
    code: str

class UrlError(CobbleError): ...
class FileSystemError(CobbleError): ...
class IoError(CobbleError): ...
class MemtableFullError(CobbleError): ...
class ConfigurationError(CobbleError): ...
class InputError(CobbleError): ...
class CoordinationError(CobbleError): ...
class InternalStateError(CobbleError): ...
class FileFormatError(CobbleError): ...
class ChecksumError(CobbleError): ...
class CancelledError(CobbleError): ...

class RecoveryMode(IntEnum):
    SnapshotOnly = 0
    LatestWithWal = 1

class OwnedBytes:
    def __len__(self) -> int: ...
    def __bytes__(self) -> bytes: ...
    def to_bytes(self) -> bytes: ...
    def view(self) -> memoryview: ...

class ReadOptions:
    def __init__(
        self,
        *,
        column_family: str | None = None,
        columns: list[int] | None = None,
    ) -> None: ...
    @property
    def column_family(self) -> str | None: ...
    @property
    def columns(self) -> list[int] | None: ...

class WriteOptions:
    def __init__(
        self,
        *,
        ttl_seconds: int | None = None,
        column_family: str | None = None,
        await_durable: bool = True,
    ) -> None: ...
    @property
    def ttl_seconds(self) -> int | None: ...
    @property
    def column_family(self) -> str | None: ...
    @property
    def await_durable(self) -> bool: ...

class ScanOptions:
    def __init__(
        self,
        *,
        column_family: str | None = None,
        columns: list[int] | None = None,
        read_ahead_bytes: int = 0,
        max_rows: int | None = None,
        preload_scan_cursor_block: bool = False,
        stop_at_block_boundary: bool = False,
    ) -> None: ...

class OwnedRow:
    @property
    def found(self) -> bool: ...
    @property
    def column_count(self) -> int: ...
    def has_column(self, column: int) -> bool: ...
    def column(self, column: int) -> OwnedBytes | None: ...
    def __bool__(self) -> bool: ...

class ScanRow:
    @property
    def bucket(self) -> int: ...
    @property
    def key(self) -> OwnedBytes: ...
    @property
    def column_count(self) -> int: ...
    def has_column(self, column: int) -> bool: ...
    def column(self, column: int) -> OwnedBytes | None: ...

class OwnedBatch:
    def __len__(self) -> int: ...
    def row(self, index: int) -> ScanRow: ...
    @property
    def end(self) -> bool: ...
    @property
    def stopped_at_block_boundary(self) -> bool: ...

class ScanCursor:
    def next(self, max_rows: int) -> OwnedBatch: ...
    def resume_after_block_boundary(self) -> None: ...
    def close(self) -> None: ...
    def __enter__(self) -> ScanCursor: ...
    def __exit__(self, exception_type: object, exception: object, traceback: object) -> bool: ...

class SingleDb:
    @staticmethod
    def open(config_json: str) -> SingleDb: ...
    @staticmethod
    def open_file(config_path: str | PathLike[str]) -> SingleDb: ...
    @staticmethod
    def resume(
        config_json: str,
        snapshot_id: int,
        recovery_mode: RecoveryMode = RecoveryMode.SnapshotOnly,
    ) -> SingleDb: ...
    @staticmethod
    def resume_file(
        config_path: str | PathLike[str],
        snapshot_id: int,
        recovery_mode: RecoveryMode = RecoveryMode.SnapshotOnly,
    ) -> SingleDb: ...
    def put(self, bucket: int, key: bytes | bytearray, column: int, value: bytes | bytearray, options: WriteOptions | None = None) -> None: ...
    def merge(self, bucket: int, key: bytes | bytearray, column: int, value: bytes | bytearray, options: WriteOptions | None = None) -> None: ...
    def delete(self, bucket: int, key: bytes | bytearray, column: int, options: WriteOptions | None = None) -> None: ...
    def get(self, bucket: int, key: bytes | bytearray, options: ReadOptions | None = None) -> OwnedRow: ...
    def scan(self, bucket: int, start: bytes | bytearray | None = None, end: bytes | bytearray | None = None, options: ScanOptions | None = None) -> ScanCursor: ...
    def snapshot(self) -> int: ...
    def retain_snapshot(self, snapshot_id: int) -> bool: ...
    def expire_snapshot(self, snapshot_id: int) -> bool: ...
    def list_snapshots(self) -> list[int]: ...
    def set_time(self, unix_seconds: int) -> None: ...
    def close(self) -> None: ...
    def __enter__(self) -> SingleDb: ...
    def __exit__(self, exception_type: object, exception: object, traceback: object) -> bool: ...

Database: TypeAlias = SingleDb
