from enum import IntEnum
from os import PathLike
from typing import Final, TypeAlias

__version__: Final[str]

class CobbleError(Exception):
    code: str

class UrlError(CobbleError): ...
class FileSystemError(CobbleError): ...
class IoError(CobbleError): ...
class MemtableFullError(CobbleError): ...
class ConfigurationError(CobbleError): ...
class InputError(CobbleError): ...
class CoordinationError(CobbleError): ...
class InternalStateError(CobbleError): ...
class FileFormatError(CobbleError): ...
class ChecksumError(CobbleError): ...
class CancelledError(CobbleError): ...

class RecoveryMode(IntEnum):
    SnapshotOnly = 0
    LatestWithWal = 1

class MemtableType(IntEnum):
    Hash = 0
    Skiplist = 1
    Vec = 2
    Adaptive = 3

class ExpandStorageMode(IntEnum):
    AdoptAsync = 0
    ReferencePersistent = 1
    ReferencePersistentWithCache = 2

class ReaderMode(IntEnum):
    Current = 0
    Snapshot = 1

class BufferStatus(IntEnum):
    Ok = 0
    NotFound = 1
    End = 2
    BufferTooSmall = 3
    BlockBoundary = 4

class BufferResult:
    @property
    def status(self) -> BufferStatus: ...
    @property
    def bytes_written(self) -> int: ...
    @property
    def bytes_required(self) -> int: ...
    @property
    def row_count(self) -> int: ...

class OwnedBytes:
    def __len__(self) -> int: ...
    def __bytes__(self) -> bytes: ...
    def to_bytes(self) -> bytes: ...
    def view(self) -> memoryview: ...

class ReadOptions:
    def __init__(
        self,
        *,
        column_family: str | None = None,
        columns: list[int] | None = None,
    ) -> None: ...
    @property
    def column_family(self) -> str | None: ...
    @property
    def columns(self) -> list[int] | None: ...

class WriteOptions:
    def __init__(
        self,
        *,
        ttl_seconds: int | None = None,
        column_family: str | None = None,
        await_durable: bool = True,
    ) -> None: ...
    @property
    def ttl_seconds(self) -> int | None: ...
    @property
    def column_family(self) -> str | None: ...
    @property
    def await_durable(self) -> bool: ...

class ScanOptions:
    def __init__(
        self,
        *,
        column_family: str | None = None,
        columns: list[int] | None = None,
        read_ahead_bytes: int = 0,
        max_rows: int | None = None,
        preload_scan_cursor_block: bool = False,
        stop_at_block_boundary: bool = False,
    ) -> None: ...

class OwnedRow:
    @property
    def found(self) -> bool: ...
    @property
    def column_count(self) -> int: ...
    def has_column(self, column: int) -> bool: ...
    def column(self, column: int) -> OwnedBytes | None: ...
    def __bool__(self) -> bool: ...

class ScanRow:
    @property
    def bucket(self) -> int: ...
    @property
    def key(self) -> OwnedBytes: ...
    @property
    def column_count(self) -> int: ...
    def has_column(self, column: int) -> bool: ...
    def column(self, column: int) -> OwnedBytes | None: ...

class OwnedMultiGetResult:
    def __len__(self) -> int: ...
    def row(self, index: int) -> OwnedRow: ...

class OwnedBatch:
    def __len__(self) -> int: ...
    def row(self, index: int) -> ScanRow: ...
    @property
    def end(self) -> bool: ...
    @property
    def stopped_at_block_boundary(self) -> bool: ...

class ScanCursor:
    def next(self, max_rows: int) -> OwnedBatch: ...
    def next_batch_into(self, max_rows: int, output: bytearray | memoryview) -> BufferResult: ...
    def resume_after_block_boundary(self) -> None: ...
    def close(self) -> None: ...
    def __enter__(self) -> ScanCursor: ...
    def __exit__(self, exception_type: object, exception: object, traceback: object) -> bool: ...

class WriteBatch:
    def __init__(self) -> None: ...
    def put(self, bucket: int, key: bytes | bytearray | memoryview, column: int, value: bytes | bytearray | memoryview, options: WriteOptions | None = None) -> None: ...
    def merge(self, bucket: int, key: bytes | bytearray | memoryview, column: int, value: bytes | bytearray | memoryview, options: WriteOptions | None = None) -> None: ...
    def delete(self, bucket: int, key: bytes | bytearray | memoryview, column: int, options: WriteOptions | None = None) -> None: ...
    def clear(self) -> None: ...
    def __len__(self) -> int: ...
    def __bool__(self) -> bool: ...

class BucketRange:
    def __init__(self, start_inclusive: int, end_inclusive: int) -> None: ...
    @property
    def start_inclusive(self) -> int: ...
    @property
    def end_inclusive(self) -> int: ...

class ColumnFamilyId:
    def __init__(self, name: str, id: int) -> None: ...
    @property
    def name(self) -> str: ...
    @property
    def id(self) -> int: ...

class ShardSnapshot:
    def __init__(
        self,
        ranges: list[BucketRange],
        column_families: list[ColumnFamilyId],
        db_id: str,
        snapshot_id: int,
        manifest_path: str,
        timestamp_seconds: int,
        data_size_bytes: int,
        incremental_data_size_bytes: int,
    ) -> None: ...
    @property
    def ranges(self) -> list[BucketRange]: ...
    @property
    def column_families(self) -> list[ColumnFamilyId]: ...
    @property
    def db_id(self) -> str: ...
    @property
    def snapshot_id(self) -> int: ...
    @property
    def manifest_path(self) -> str: ...
    @property
    def timestamp_seconds(self) -> int: ...
    @property
    def data_size_bytes(self) -> int: ...
    @property
    def incremental_data_size_bytes(self) -> int: ...

class GlobalSnapshot:
    @property
    def version(self) -> int: ...
    @property
    def id(self) -> int: ...
    @property
    def total_buckets(self) -> int: ...
    @property
    def column_families(self) -> list[ColumnFamilyId]: ...
    @property
    def shards(self) -> list[ShardSnapshot]: ...
    @property
    def watermark_seconds(self) -> int: ...

class PendingSnapshot:
    @property
    def id(self) -> int: ...
    def wait(self) -> GlobalSnapshot: ...

class PendingShardSnapshot:
    @property
    def id(self) -> int: ...
    def wait(self) -> ShardSnapshot: ...

class MergeOperatorSpec:
    @property
    def id(self) -> str: ...
    @property
    def metadata_json(self) -> str | None: ...

class ColumnFamily:
    @property
    def name(self) -> str: ...
    @property
    def id(self) -> int: ...
    @property
    def column_count(self) -> int: ...
    @property
    def value_has_ttl(self) -> bool: ...
    @property
    def merge_operators(self) -> list[MergeOperatorSpec]: ...

class Schema:
    @property
    def version(self) -> int: ...
    @property
    def column_families(self) -> list[ColumnFamily]: ...

class SchemaBuilder:
    def set_column_operator(
        self,
        column: int,
        operator_id: str,
        *,
        metadata_json: str | None = None,
        column_family: str | None = None,
    ) -> None: ...
    def add_column(
        self,
        column: int,
        *,
        operator_id: str | None = None,
        metadata_json: str | None = None,
        default_value: bytes | bytearray | memoryview | None = None,
        column_family: str | None = None,
    ) -> None: ...
    def delete_column(self, column: int, *, column_family: str | None = None) -> None: ...
    def set_column_family_ttl(self, value_has_ttl: bool, *, column_family: str | None = None) -> None: ...
    def commit(self) -> Schema: ...

class MetricLabel:
    @property
    def key(self) -> str: ...
    @property
    def value(self) -> str: ...

class CounterValue:
    @property
    def value(self) -> int: ...

class GaugeValue:
    @property
    def value(self) -> float: ...

class HistogramValue:
    @property
    def count(self) -> int: ...
    @property
    def sum(self) -> float: ...
    @property
    def min(self) -> float: ...
    @property
    def max(self) -> float: ...

MetricValue: TypeAlias = CounterValue | GaugeValue | HistogramValue

class MetricSample:
    @property
    def name(self) -> str: ...
    @property
    def labels(self) -> list[MetricLabel]: ...
    @property
    def value(self) -> MetricValue: ...

class Reader:
    @staticmethod
    def open_current(config_json: str) -> Reader: ...
    @staticmethod
    def open_current_file(config_path: str | PathLike[str]) -> Reader: ...
    @staticmethod
    def open(config_json: str, snapshot_id: int) -> Reader: ...
    @staticmethod
    def open_file(config_path: str | PathLike[str], snapshot_id: int) -> Reader: ...
    def refresh(self) -> None: ...
    def get(self, bucket: int, key: bytes | bytearray | memoryview, options: ReadOptions | None = None) -> OwnedRow: ...
    def multi_get(self, keys: list[tuple[int, bytes | bytearray | memoryview]], options: ReadOptions | None = None) -> OwnedMultiGetResult: ...
    def get_column_into(self, bucket: int, key: bytes | bytearray | memoryview, output: bytearray | memoryview, options: ReadOptions) -> BufferResult: ...
    def scan(self, bucket: int, start: bytes | bytearray | memoryview, end: bytes | bytearray | memoryview, options: ScanOptions | None = None) -> ScanCursor: ...
    @property
    def mode(self) -> ReaderMode: ...
    @property
    def configured_snapshot_id(self) -> int | None: ...
    @property
    def current_global_snapshot(self) -> GlobalSnapshot: ...
    def list_global_snapshots(self) -> list[GlobalSnapshot]: ...

class ReadOnlyDb:
    @staticmethod
    def open(config_json: str, snapshot_id: int, db_id: str) -> ReadOnlyDb: ...
    @staticmethod
    def open_file(config_path: str | PathLike[str], snapshot_id: int, db_id: str) -> ReadOnlyDb: ...
    @property
    def id(self) -> str: ...
    def get(self, bucket: int, key: bytes | bytearray | memoryview, options: ReadOptions | None = None) -> OwnedRow: ...
    def multi_get(self, keys: list[tuple[int, bytes | bytearray | memoryview]], options: ReadOptions | None = None) -> OwnedMultiGetResult: ...
    def get_column_into(self, bucket: int, key: bytes | bytearray | memoryview, output: bytearray | memoryview, options: ReadOptions) -> BufferResult: ...
    def scan(self, bucket: int, start: bytes | bytearray | memoryview | None = None, end: bytes | bytearray | memoryview | None = None, options: ScanOptions | None = None) -> ScanCursor: ...
    def current_schema(self) -> Schema: ...
    def metrics(self) -> list[MetricSample]: ...

class DbCoordinator:
    @staticmethod
    def open(config_json: str) -> DbCoordinator: ...
    @staticmethod
    def open_file(config_path: str | PathLike[str]) -> DbCoordinator: ...
    def materialize_global_snapshot(self, total_buckets: int, snapshot_id: int, shards: list[ShardSnapshot]) -> GlobalSnapshot: ...
    def get_global_snapshot(self, snapshot_id: int) -> GlobalSnapshot: ...
    def list_global_snapshots(self) -> list[GlobalSnapshot]: ...
    def load_current_global_snapshot(self) -> GlobalSnapshot | None: ...
    def retain_snapshot(self, snapshot_id: int) -> bool: ...
    def expire_snapshot(self, snapshot_id: int) -> bool: ...

class ScanSplitBoundary:
    @property
    def bucket(self) -> int: ...
    @property
    def key(self) -> bytes: ...

class ScanSplitPartition:
    @property
    def before(self) -> ScanSplit: ...
    @property
    def after(self) -> ScanSplit: ...

class ScanSplit:
    @property
    def shard(self) -> ShardSnapshot: ...
    @property
    def start_inclusive(self) -> bytes | None: ...
    @property
    def end_exclusive(self) -> bytes | None: ...
    @property
    def start_after_exclusive(self) -> ScanSplitBoundary | None: ...
    @property
    def end_at_inclusive(self) -> ScanSplitBoundary | None: ...
    def split_after(self, bucket: int, key_inclusive: bytes | bytearray | memoryview) -> ScanSplitPartition: ...
    def to_json(self) -> str: ...
    @staticmethod
    def from_json(json: str) -> ScanSplit: ...
    def open_scanner(self, config_json: str, options: ScanOptions | None = None) -> ScanCursor: ...
    def open_scanner_file(self, config_path: str | PathLike[str], options: ScanOptions | None = None) -> ScanCursor: ...

class ScanPlan:
    @staticmethod
    def from_global_snapshot(snapshot: GlobalSnapshot) -> ScanPlan: ...
    def with_start(self, start_inclusive: bytes | bytearray | memoryview) -> None: ...
    def with_end(self, end_exclusive: bytes | bytearray | memoryview) -> None: ...
    def without_start(self) -> None: ...
    def without_end(self) -> None: ...
    def splits(self) -> list[ScanSplit]: ...

class SingleDb:
    @staticmethod
    def open(config_json: str) -> SingleDb: ...
    @staticmethod
    def open_file(config_path: str | PathLike[str]) -> SingleDb: ...
    @staticmethod
    def resume(
        config_json: str,
        snapshot_id: int,
        recovery_mode: RecoveryMode = RecoveryMode.SnapshotOnly,
    ) -> SingleDb: ...
    @staticmethod
    def resume_file(
        config_path: str | PathLike[str],
        snapshot_id: int,
        recovery_mode: RecoveryMode = RecoveryMode.SnapshotOnly,
    ) -> SingleDb: ...
    def put(self, bucket: int, key: bytes | bytearray | memoryview, column: int, value: bytes | bytearray | memoryview, options: WriteOptions | None = None) -> None: ...
    def merge(self, bucket: int, key: bytes | bytearray | memoryview, column: int, value: bytes | bytearray | memoryview, options: WriteOptions | None = None) -> None: ...
    def delete(self, bucket: int, key: bytes | bytearray | memoryview, column: int, options: WriteOptions | None = None) -> None: ...
    def get(self, bucket: int, key: bytes | bytearray | memoryview, options: ReadOptions | None = None) -> OwnedRow: ...
    def multi_get(self, keys: list[tuple[int, bytes | bytearray | memoryview]], options: ReadOptions | None = None) -> OwnedMultiGetResult: ...
    def get_column_into(self, bucket: int, key: bytes | bytearray | memoryview, output: bytearray | memoryview, options: ReadOptions) -> BufferResult: ...
    def write(self, batch: WriteBatch, *, await_durable: bool = True) -> None: ...
    def scan(self, bucket: int, start: bytes | bytearray | memoryview | None = None, end: bytes | bytearray | memoryview | None = None, options: ScanOptions | None = None) -> ScanCursor: ...
    def snapshot(self) -> int: ...
    def start_snapshot(self) -> PendingSnapshot: ...
    def take_snapshot(self) -> GlobalSnapshot: ...
    def get_snapshot(self, snapshot_id: int) -> GlobalSnapshot: ...
    def list_global_snapshots(self) -> list[GlobalSnapshot]: ...
    def retain_snapshot(self, snapshot_id: int) -> bool: ...
    def expire_snapshot(self, snapshot_id: int) -> bool: ...
    def list_snapshots(self) -> list[int]: ...
    def set_time(self, unix_seconds: int) -> None: ...
    def now_seconds(self) -> int: ...
    def switch_memtable_type(self, memtable_type: MemtableType, *, flush_current: bool = False) -> None: ...
    def load_readonly_files_to_primary(self) -> int: ...
    def current_schema(self) -> Schema: ...
    def update_schema(self) -> SchemaBuilder: ...
    def metrics(self) -> list[MetricSample]: ...
    def close(self) -> None: ...
    def __enter__(self) -> SingleDb: ...
    def __exit__(self, exception_type: object, exception: object, traceback: object) -> bool: ...

Database: TypeAlias = SingleDb

class Db:
    @staticmethod
    def open(config_json: str, ranges: list[BucketRange] | None = None) -> Db: ...
    @staticmethod
    def open_file(config_path: str | PathLike[str], ranges: list[BucketRange] | None = None) -> Db: ...
    @staticmethod
    def open_from_snapshot(
        config_json: str,
        snapshot_id: int,
        db_id: str,
        recovery_mode: RecoveryMode = RecoveryMode.SnapshotOnly,
    ) -> Db: ...
    @staticmethod
    def open_from_snapshot_file(
        config_path: str | PathLike[str],
        snapshot_id: int,
        db_id: str,
        recovery_mode: RecoveryMode = RecoveryMode.SnapshotOnly,
    ) -> Db: ...
    @staticmethod
    def restore_new(config_json: str, snapshot_id: int, source_db_id: str) -> Db: ...
    @staticmethod
    def restore_new_file(config_path: str | PathLike[str], snapshot_id: int, source_db_id: str) -> Db: ...
    @staticmethod
    def restore_new_from_manifest(config_json: str, manifest_path: str) -> Db: ...
    @staticmethod
    def restore_new_from_manifest_file(config_path: str | PathLike[str], manifest_path: str) -> Db: ...
    @staticmethod
    def resume(
        config_json: str,
        db_id: str,
        recovery_mode: RecoveryMode = RecoveryMode.LatestWithWal,
    ) -> Db: ...
    @staticmethod
    def resume_file(
        config_path: str | PathLike[str],
        db_id: str,
        recovery_mode: RecoveryMode = RecoveryMode.LatestWithWal,
    ) -> Db: ...
    @staticmethod
    def resume_from_snapshot(
        config_json: str,
        snapshot_id: int,
        db_id: str,
        recovery_mode: RecoveryMode = RecoveryMode.SnapshotOnly,
    ) -> Db: ...
    @staticmethod
    def resume_from_snapshot_file(
        config_path: str | PathLike[str],
        snapshot_id: int,
        db_id: str,
        recovery_mode: RecoveryMode = RecoveryMode.SnapshotOnly,
    ) -> Db: ...
    @property
    def id(self) -> str: ...
    def put(self, bucket: int, key: bytes | bytearray | memoryview, column: int, value: bytes | bytearray | memoryview, options: WriteOptions | None = None) -> None: ...
    def merge(self, bucket: int, key: bytes | bytearray | memoryview, column: int, value: bytes | bytearray | memoryview, options: WriteOptions | None = None) -> None: ...
    def delete(self, bucket: int, key: bytes | bytearray | memoryview, column: int, options: WriteOptions | None = None) -> None: ...
    def get(self, bucket: int, key: bytes | bytearray | memoryview, options: ReadOptions | None = None) -> OwnedRow: ...
    def multi_get(self, keys: list[tuple[int, bytes | bytearray | memoryview]], options: ReadOptions | None = None) -> OwnedMultiGetResult: ...
    def get_column_into(self, bucket: int, key: bytes | bytearray | memoryview, output: bytearray | memoryview, options: ReadOptions) -> BufferResult: ...
    def write(self, batch: WriteBatch, *, await_durable: bool = True) -> None: ...
    def scan(self, bucket: int, start: bytes | bytearray | memoryview | None = None, end: bytes | bytearray | memoryview | None = None, options: ScanOptions | None = None) -> ScanCursor: ...
    def snapshot(self) -> int: ...
    def start_snapshot(self) -> PendingShardSnapshot: ...
    def take_snapshot(self) -> ShardSnapshot: ...
    def cancel_snapshot(self, snapshot_id: int) -> bool: ...
    def get_shard_snapshot(self, snapshot_id: int) -> ShardSnapshot: ...
    def retain_snapshot(self, snapshot_id: int) -> bool: ...
    def expire_snapshot(self, snapshot_id: int) -> bool: ...
    def switch_to_snapshot(self, snapshot_id: int) -> None: ...
    def expand_bucket(
        self,
        source_db_id: str,
        *,
        source_snapshot: int | None = None,
        ranges: list[BucketRange] | None = None,
        storage_mode: ExpandStorageMode = ExpandStorageMode.AdoptAsync,
    ) -> int: ...
    def wait_for_expand_adoption(self, timeout_seconds: float) -> None: ...
    def shrink_bucket(self, ranges: list[BucketRange]) -> int: ...
    def current_schema(self) -> Schema: ...
    def update_schema(self) -> SchemaBuilder: ...
    def metrics(self) -> list[MetricSample]: ...
    def set_time(self, unix_seconds: int) -> None: ...
    def now_seconds(self) -> int: ...
    def switch_memtable_type(self, memtable_type: MemtableType, *, flush_current: bool = False) -> None: ...
    def load_readonly_files_to_primary(self) -> int: ...
    def close(self) -> None: ...
    def __enter__(self) -> Db: ...
    def __exit__(self, exception_type: object, exception: object, traceback: object) -> bool: ...

class StructuredColumnKind(IntEnum):
    Bytes = 0
    List = 1

class ListRetainMode(IntEnum):
    First = 0
    Last = 1

class ListConfig:
    def __init__(self, *, max_elements: int | None = None, retain_mode: ListRetainMode = ListRetainMode.Last, preserve_element_ttl: bool = False) -> None: ...
    @property
    def max_elements(self) -> int | None: ...
    @property
    def retain_mode(self) -> ListRetainMode: ...
    @property
    def preserve_element_ttl(self) -> bool: ...

class StructuredReadOptions:
    def __init__(self, *, column_family: str | None = None, columns: list[int] | None = None) -> None: ...

class StructuredScanOptions:
    def __init__(self, *, column_family: str | None = None, columns: list[int] | None = None, preload_scan_cursor_block: bool = False, stop_at_block_boundary: bool = False) -> None: ...

class StructuredRow:
    @property
    def found(self) -> bool: ...
    @property
    def column_count(self) -> int: ...
    def has_column(self, column: int) -> bool: ...
    def kind(self, column: int) -> StructuredColumnKind: ...
    def bytes(self, column: int) -> OwnedBytes: ...
    def list_size(self, column: int) -> int: ...
    def list_element(self, column: int, element: int) -> OwnedBytes: ...
    def __bool__(self) -> bool: ...

class StructuredMultiGetResult:
    def __len__(self) -> int: ...
    def row(self, index: int) -> StructuredRow: ...

class StructuredWriteBatch:
    def __init__(self) -> None: ...
    def put_bytes(self, bucket: int, key: bytes | bytearray | memoryview, column: int, value: bytes | bytearray | memoryview, options: WriteOptions | None = None) -> None: ...
    def merge_bytes(self, bucket: int, key: bytes | bytearray | memoryview, column: int, value: bytes | bytearray | memoryview, options: WriteOptions | None = None) -> None: ...
    def put_list(self, bucket: int, key: bytes | bytearray | memoryview, column: int, values: list[bytes | bytearray | memoryview], options: WriteOptions | None = None) -> None: ...
    def merge_list(self, bucket: int, key: bytes | bytearray | memoryview, column: int, values: list[bytes | bytearray | memoryview], options: WriteOptions | None = None) -> None: ...
    def delete(self, bucket: int, key: bytes | bytearray | memoryview, column: int, options: WriteOptions | None = None) -> None: ...
    def clear(self) -> None: ...
    def __len__(self) -> int: ...
    def __bool__(self) -> bool: ...

class StructuredColumn:
    @property
    def index(self) -> int: ...
    @property
    def kind(self) -> StructuredColumnKind: ...
    @property
    def list_config(self) -> ListConfig | None: ...

class StructuredFamily:
    @property
    def name(self) -> str: ...
    @property
    def id(self) -> int: ...
    @property
    def columns(self) -> list[StructuredColumn]: ...

class StructuredSchema:
    @property
    def families(self) -> list[StructuredFamily]: ...

class StructuredSchemaBuilder:
    def add_bytes_column(self, column: int, *, column_family: str | None = None) -> None: ...
    def add_list_column(self, column: int, config: ListConfig, *, column_family: str | None = None) -> None: ...
    def delete_column(self, column: int, *, column_family: str | None = None) -> None: ...
    def set_column_family_ttl(self, value_has_ttl: bool, *, column_family: str | None = None) -> None: ...
    def commit(self) -> StructuredSchema: ...

class StructuredScanRow:
    @property
    def bucket(self) -> int: ...
    @property
    def key(self) -> OwnedBytes: ...
    @property
    def value(self) -> StructuredRow: ...

class StructuredBatch:
    def __len__(self) -> int: ...
    def row(self, index: int) -> StructuredScanRow: ...
    @property
    def end(self) -> bool: ...
    @property
    def stopped_at_block_boundary(self) -> bool: ...

class StructuredScanCursor:
    def next(self, max_rows: int) -> StructuredBatch: ...
    def next_into(self, max_rows: int, output: bytearray | memoryview) -> BufferResult: ...
    def resume_after_block_boundary(self) -> None: ...
    def close(self) -> None: ...

class StructuredScanSplitBoundary:
    @property
    def bucket(self) -> int: ...
    @property
    def key(self) -> bytes: ...

class StructuredScanSplitPartition:
    @property
    def before(self) -> StructuredScanSplit: ...
    @property
    def after(self) -> StructuredScanSplit: ...

class StructuredScanSplit:
    @property
    def shard(self) -> ShardSnapshot: ...
    @property
    def start_inclusive(self) -> bytes | None: ...
    @property
    def end_exclusive(self) -> bytes | None: ...
    @property
    def start_after_exclusive(self) -> StructuredScanSplitBoundary | None: ...
    @property
    def end_at_inclusive(self) -> StructuredScanSplitBoundary | None: ...
    def split_after(self, bucket: int, key_inclusive: bytes | bytearray | memoryview) -> StructuredScanSplitPartition: ...
    def to_json(self) -> str: ...
    @staticmethod
    def from_json(json: str) -> StructuredScanSplit: ...
    def open_scanner(self, config_json: str, options: StructuredScanOptions | None = None) -> StructuredScanCursor: ...
    def open_scanner_file(self, config_path: str | PathLike[str], options: StructuredScanOptions | None = None) -> StructuredScanCursor: ...

class StructuredScanPlan:
    @staticmethod
    def from_global_snapshot(snapshot: GlobalSnapshot) -> StructuredScanPlan: ...
    def with_start(self, start_inclusive: bytes | bytearray | memoryview) -> None: ...
    def with_end(self, end_exclusive: bytes | bytearray | memoryview) -> None: ...
    def without_start(self) -> None: ...
    def without_end(self) -> None: ...
    def splits(self) -> list[StructuredScanSplit]: ...

class PriorityQueueEntry:
    @property
    def key(self) -> OwnedBytes: ...
    @property
    def value(self) -> OwnedBytes: ...

class PriorityQueueBatch:
    def __len__(self) -> int: ...
    def entry(self, index: int) -> PriorityQueueEntry: ...

class PriorityQueue:
    @property
    def column_family(self) -> str: ...
    def offer(self, bucket: int, key: bytes | bytearray | memoryview, value: bytes | bytearray | memoryview) -> None: ...
    def delete(self, bucket: int, key: bytes | bytearray | memoryview) -> None: ...
    def peek(self, bucket: int) -> PriorityQueueEntry | None: ...
    def poll(self, bucket: int) -> PriorityQueueEntry | None: ...
    def peek_batch(self, bucket: int, limit: int | None = None) -> PriorityQueueBatch: ...
    def poll_batch(self, bucket: int, limit: int | None = None) -> PriorityQueueBatch: ...
    def advance(self, bucket: int, key: bytes | bytearray | memoryview) -> None: ...
    def cursor(self, bucket: int) -> bytes | None: ...
    def peek_into(self, bucket: int, output: bytearray | memoryview) -> BufferResult: ...
    def poll_into(self, bucket: int, output: bytearray | memoryview) -> BufferResult: ...
    def peek_batch_into(self, bucket: int, output: bytearray | memoryview, limit: int | None = None) -> BufferResult: ...
    def poll_batch_into(self, bucket: int, output: bytearray | memoryview, limit: int | None = None) -> BufferResult: ...

class StructuredSingleDb:
    @staticmethod
    def open(config_json: str) -> StructuredSingleDb: ...
    @staticmethod
    def open_file(config_path: str | PathLike[str]) -> StructuredSingleDb: ...
    def put_bytes(self, bucket: int, key: bytes | bytearray | memoryview, column: int, value: bytes | bytearray | memoryview, options: WriteOptions | None = None) -> None: ...
    def put_list(self, bucket: int, key: bytes | bytearray | memoryview, column: int, elements: list[bytes | bytearray | memoryview], options: WriteOptions | None = None) -> None: ...
    def merge_bytes(self, bucket: int, key: bytes | bytearray | memoryview, column: int, value: bytes | bytearray | memoryview, options: WriteOptions | None = None) -> None: ...
    def merge_list(self, bucket: int, key: bytes | bytearray | memoryview, column: int, elements: list[bytes | bytearray | memoryview], options: WriteOptions | None = None) -> None: ...
    def delete(self, bucket: int, key: bytes | bytearray | memoryview, column: int, options: WriteOptions | None = None) -> None: ...
    def get(self, bucket: int, key: bytes | bytearray | memoryview, options: StructuredReadOptions | None = None) -> StructuredRow: ...
    def get_into(self, bucket: int, key: bytes | bytearray | memoryview, output: bytearray | memoryview, options: StructuredReadOptions | None = None) -> BufferResult: ...
    def multi_get(self, keys: list[tuple[int, bytes | bytearray | memoryview]], options: StructuredReadOptions | None = None) -> StructuredMultiGetResult: ...
    def multi_get_into(self, keys: list[tuple[int, bytes | bytearray | memoryview]], output: bytearray | memoryview, options: StructuredReadOptions | None = None) -> BufferResult: ...
    def write(self, batch: StructuredWriteBatch) -> None: ...
    def scan(self, bucket: int, start: bytes | bytearray | memoryview | None = None, end: bytes | bytearray | memoryview | None = None, options: StructuredScanOptions | None = None) -> StructuredScanCursor: ...
    def current_schema(self) -> StructuredSchema: ...
    def update_schema(self) -> StructuredSchemaBuilder: ...
    def new_priority_queue(self, name: str) -> PriorityQueue: ...
    def get_priority_queue(self, name: str) -> PriorityQueue: ...
    def get_or_new_priority_queue(self, name: str) -> PriorityQueue: ...
    def snapshot(self) -> int: ...
    def start_snapshot(self) -> PendingSnapshot: ...
    def take_snapshot(self) -> GlobalSnapshot: ...
    def get_snapshot(self, snapshot_id: int) -> GlobalSnapshot: ...
    def list_snapshots(self) -> list[GlobalSnapshot]: ...
    def retain_snapshot(self, snapshot_id: int) -> bool: ...
    def expire_snapshot(self, snapshot_id: int) -> bool: ...
    def set_time(self, unix_seconds: int) -> None: ...
    def now_seconds(self) -> int: ...
    def switch_memtable_type(self, memtable_type: MemtableType, *, flush_current: bool = False) -> None: ...
    def load_readonly_files_to_primary(self) -> int: ...
    def close(self) -> None: ...
    def __enter__(self) -> StructuredSingleDb: ...
    def __exit__(self, exception_type: object, exception: object, traceback: object) -> bool: ...

class StructuredDb:
    @staticmethod
    def open(config_json: str, ranges: list[BucketRange] | None = None) -> StructuredDb: ...
    @staticmethod
    def open_file(config_path: str | PathLike[str], ranges: list[BucketRange] | None = None) -> StructuredDb: ...
    @staticmethod
    def open_from_snapshot(config_json: str, snapshot_id: int, db_id: str, recovery_mode: RecoveryMode = RecoveryMode.SnapshotOnly) -> StructuredDb: ...
    @staticmethod
    def open_from_snapshot_file(config_path: str | PathLike[str], snapshot_id: int, db_id: str, recovery_mode: RecoveryMode = RecoveryMode.SnapshotOnly) -> StructuredDb: ...
    @staticmethod
    def restore_new(config_json: str, snapshot_id: int, source_db_id: str) -> StructuredDb: ...
    @staticmethod
    def restore_new_file(config_path: str | PathLike[str], snapshot_id: int, source_db_id: str) -> StructuredDb: ...
    @staticmethod
    def restore_new_from_manifest(config_json: str, manifest_path: str) -> StructuredDb: ...
    @staticmethod
    def restore_new_from_manifest_file(config_path: str | PathLike[str], manifest_path: str) -> StructuredDb: ...
    @staticmethod
    def resume(config_json: str, db_id: str, recovery_mode: RecoveryMode = RecoveryMode.LatestWithWal) -> StructuredDb: ...
    @staticmethod
    def resume_file(config_path: str | PathLike[str], db_id: str, recovery_mode: RecoveryMode = RecoveryMode.LatestWithWal) -> StructuredDb: ...
    @staticmethod
    def resume_from_snapshot(config_json: str, snapshot_id: int, db_id: str, recovery_mode: RecoveryMode = RecoveryMode.SnapshotOnly) -> StructuredDb: ...
    @staticmethod
    def resume_from_snapshot_file(config_path: str | PathLike[str], snapshot_id: int, db_id: str, recovery_mode: RecoveryMode = RecoveryMode.SnapshotOnly) -> StructuredDb: ...
    @property
    def id(self) -> str: ...
    def put_bytes(self, bucket: int, key: bytes | bytearray | memoryview, column: int, value: bytes | bytearray | memoryview, options: WriteOptions | None = None) -> None: ...
    def put_list(self, bucket: int, key: bytes | bytearray | memoryview, column: int, elements: list[bytes | bytearray | memoryview], options: WriteOptions | None = None) -> None: ...
    def merge_bytes(self, bucket: int, key: bytes | bytearray | memoryview, column: int, value: bytes | bytearray | memoryview, options: WriteOptions | None = None) -> None: ...
    def merge_list(self, bucket: int, key: bytes | bytearray | memoryview, column: int, elements: list[bytes | bytearray | memoryview], options: WriteOptions | None = None) -> None: ...
    def delete(self, bucket: int, key: bytes | bytearray | memoryview, column: int, options: WriteOptions | None = None) -> None: ...
    def get(self, bucket: int, key: bytes | bytearray | memoryview, options: StructuredReadOptions | None = None) -> StructuredRow: ...
    def get_into(self, bucket: int, key: bytes | bytearray | memoryview, output: bytearray | memoryview, options: StructuredReadOptions | None = None) -> BufferResult: ...
    def multi_get(self, keys: list[tuple[int, bytes | bytearray | memoryview]], options: StructuredReadOptions | None = None) -> StructuredMultiGetResult: ...
    def multi_get_into(self, keys: list[tuple[int, bytes | bytearray | memoryview]], output: bytearray | memoryview, options: StructuredReadOptions | None = None) -> BufferResult: ...
    def write(self, batch: StructuredWriteBatch) -> None: ...
    def scan(self, bucket: int, start: bytes | bytearray | memoryview | None = None, end: bytes | bytearray | memoryview | None = None, options: StructuredScanOptions | None = None) -> StructuredScanCursor: ...
    def current_schema(self) -> StructuredSchema: ...
    def update_schema(self) -> StructuredSchemaBuilder: ...
    def new_priority_queue(self, name: str) -> PriorityQueue: ...
    def get_priority_queue(self, name: str) -> PriorityQueue: ...
    def get_or_new_priority_queue(self, name: str) -> PriorityQueue: ...
    def snapshot(self) -> int: ...
    def start_snapshot(self) -> PendingShardSnapshot: ...
    def take_snapshot(self) -> ShardSnapshot: ...
    def cancel_snapshot(self, snapshot_id: int) -> bool: ...
    def get_shard_snapshot(self, snapshot_id: int) -> ShardSnapshot: ...
    def retain_snapshot(self, snapshot_id: int) -> bool: ...
    def expire_snapshot(self, snapshot_id: int) -> bool: ...
    def switch_to_snapshot(self, snapshot_id: int) -> None: ...
    def expand_bucket(self, source_db_id: str, *, source_snapshot: int | None = None, ranges: list[BucketRange] | None = None, storage_mode: ExpandStorageMode = ExpandStorageMode.AdoptAsync) -> int: ...
    def wait_for_expand_adoption(self, timeout_seconds: float) -> None: ...
    def shrink_bucket(self, ranges: list[BucketRange]) -> int: ...
    def metrics(self) -> list[MetricSample]: ...
    def set_time(self, unix_seconds: int) -> None: ...
    def now_seconds(self) -> int: ...
    def switch_memtable_type(self, memtable_type: MemtableType, *, flush_current: bool = False) -> None: ...
    def load_readonly_files_to_primary(self) -> int: ...
    def close(self) -> None: ...
    def __enter__(self) -> StructuredDb: ...
    def __exit__(self, exception_type: object, exception: object, traceback: object) -> bool: ...
